### ISSUE TITLE
Turning Off Busses

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/micot-infrastructure-ep-powerworld#4]
There is an issue where the effect of setting a bus's "DESIRED_STATUS" to False does result in the bus being turned off in the power flow simulation.

**Comment by rb004f** [comment]
I have adjusted the implementation to turn off all lines and components situated at deactivated buses.  There may be a better solution from powerworld, but we shall see.

**Comment by ccoffrin** [comment]
Sounds good to me.  Lets keep this issue open until we hear back from PowerWorld.

**Comment by rb004f** [comment]
Powerworld responded, and our approach for turning off buses is the supported option (turn off all connected branches)
